AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups para la infraestructura (EC2 publica + ALB)

Resources:

  # ── SG para el Application Load Balancer ────────────────────────────
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite HTTP (80) desde internet hacia el ALB
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SG-ALB

  # ── SG para las instancias EC2 ───────────────────────────────────────
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite SSH (22) y HTTP (80) desde el ALB
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: SG-EC2

Outputs:

  ALBSecurityGroupId:
    Description: ID del Security Group del ALB
    Value: !Ref ALBSecurityGroup
    Export:
      Name: security-stack-ALBSGId

  EC2SecurityGroupId:
    Description: ID del Security Group de la EC2
    Value: !Ref EC2SecurityGroup
    Export:
      Name: security-stack-EC2SGId
